// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlsfYLLWCXFn_N12awPuKS9iVHUAj6QLc',
    appId: '1:533916337351:web:fcb26a3863e8821c25eae2',
    messagingSenderId: '533916337351',
    projectId: 'pbo-ems',
    authDomain: 'pbo-ems.firebaseapp.com',
    storageBucket: 'pbo-ems.appspot.com',
    measurementId: 'G-TR7JG6T3J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0jQznxC6syr74D0l-6jkfzX3OZnsMIWQ',
    appId: '1:533916337351:android:4a9e294ce2dbd58925eae2',
    messagingSenderId: '533916337351',
    projectId: 'pbo-ems',
    storageBucket: 'pbo-ems.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHIrm6CKRNn_j_nS9zTWS5mpfnqJL4yb8',
    appId: '1:533916337351:ios:454ea030a8f3a1f325eae2',
    messagingSenderId: '533916337351',
    projectId: 'pbo-ems',
    storageBucket: 'pbo-ems.appspot.com',
    iosBundleId: 'com.example.pboEms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHIrm6CKRNn_j_nS9zTWS5mpfnqJL4yb8',
    appId: '1:533916337351:ios:97429529023fe46d25eae2',
    messagingSenderId: '533916337351',
    projectId: 'pbo-ems',
    storageBucket: 'pbo-ems.appspot.com',
    iosBundleId: 'com.example.pboEms.RunnerTests',
  );
}
